server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: users
            uri: http://localhost:8081
            predicates:
              - Path=/api/user/**
          - id: projects
            uri: http://localhost:8082
            predicates:
              - Path=/api/project/**
          - id: users-projects
            uri: http://localhost:8083
            predicates:
              - Path=/api/user-project/**