version: '3.8'

services:
  ### MySQL database for mcsv-user
  mcsv-user:
    container_name: mcsv-user
    image: mysql:8.4.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db_user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: